trigger:
- main
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: "Frontend"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.16.0
    displayName: 'Install Node.js'
  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run-script build
    displayName: 'Build Gatsby Project'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/public'
      azure_static_web_apps_api_token: $(deployment_token)
    env:
      deploymenty_token: $(DEPLOYMENT_TOKEN)